# Nice Bus-T4 Example Configuration
# For use with Nice BiDi-WiFi module or custom ESP32 hardware

esphome:
  name: gate
  friendly_name: Gate

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
  baud_rate: 0  # Disable serial logging (UART is used for Bus-T4)

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Gate Fallback"
    password: "fallback123"

web_server:
  port: 80

external_components:
  - source: components

# UART configuration for Bus-T4
# BiDi-WiFi: GPIO21 (TX), GPIO18 (RX)
# Custom hardware: adjust pins as needed
uart:
  tx_pin: GPIO21
  rx_pin: GPIO18
  baud_rate: 19200

bus_t4:
  id: bus

cover:
  - platform: bus_t4
    name: "Gate"
    id: gate
    auto_learn_timing: true
    open_duration: 20s
    close_duration: 20s
    position_report_interval: 1s

# Optional: Additional buttons for partial opening
button:
  - platform: template
    name: "Partial Open 1"
    icon: "mdi:gate-arrow-right"
    on_press:
      - lambda: id(gate).send_cmd(CMD_OPEN_PARTIAL_1);

  - platform: template
    name: "Partial Open 2"
    icon: "mdi:gate-arrow-right"
    on_press:
      - lambda: id(gate).send_cmd(CMD_OPEN_PARTIAL_2);

  - platform: template
    name: "Step-by-Step"
    icon: "mdi:gate"
    on_press:
      - lambda: id(gate).send_cmd(CMD_STEP);

# Motor controller configuration switches
# These send SET commands to change the controller's settings
switch:
  - platform: template
    name: "Auto-Close"
    icon: "mdi:timer"
    optimistic: true
    turn_on_action:
      - lambda: id(gate).set_auto_close(true);
    turn_off_action:
      - lambda: id(gate).set_auto_close(false);

  - platform: template
    name: "Photo-Close"
    icon: "mdi:camera-timer"
    optimistic: true
    turn_on_action:
      - lambda: id(gate).set_photo_close(true);
    turn_off_action:
      - lambda: id(gate).set_photo_close(false);

  - platform: template
    name: "Always Close"
    icon: "mdi:lock"
    optimistic: true
    turn_on_action:
      - lambda: id(gate).set_always_close(true);
    turn_off_action:
      - lambda: id(gate).set_always_close(false);

  - platform: template
    name: "Standby Mode"
    icon: "mdi:power-standby"
    optimistic: true
    turn_on_action:
      - lambda: id(gate).set_standby(true);
    turn_off_action:
      - lambda: id(gate).set_standby(false);

  - platform: template
    name: "Peak Mode"
    icon: "mdi:speedometer"
    optimistic: true
    turn_on_action:
      - lambda: id(gate).set_peak_mode(true);
    turn_off_action:
      - lambda: id(gate).set_peak_mode(false);

  - platform: template
    name: "Pre-Flash Warning"
    icon: "mdi:alarm-light"
    optimistic: true
    turn_on_action:
      - lambda: id(gate).set_pre_flash(true);
    turn_off_action:
      - lambda: id(gate).set_pre_flash(false);

